### ISSUE TITLE
How Maniple select best fact set？

### ISSUE THREAD

**Issue by TPCOther** [PyRepair/maniple#20]
The paper mentions that maniple is a random forest model that finds the most appropriate set of facts for each bug. But I didn't find any code about it in that repository, just enumeration of fact permutations. I can't understand how it selects the best set of facts for bugs.

**Comment by norhh** [comment]
Hi @TPCOther, you can find the notebook in the [zenodo link](https://zenodo.org/records/13182739). It is called experiment.ipynb.
Since, the model was trivial, we could do everything in the notebook.

**Comment by TPCOther** [comment]
@norhh I got it! Thank you for your reply!
